# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rrJD21tUDglPHtu4LipGSYkE8bZCpHSv/voRPuf0VTCjnKnP4CeDLBxAAT0QuBirNAfl2tKsctIPO/827qGbS+dGmp6aAW7W1j05J8fr227/RCcI/Dnr/yjsxAEmSt8JXkpj9/34zGEBoqI4txK/Gy2d7w0u6Qg8D74ZceYrCY9R3ZXOnWmJcClky8hiEdrNX5PIKHuJYaB1EOfmv/986xYFoGUVp1eCaT7KCaIT8C7ju/VwKxtbkeiqb2PveayQhrZ7a1YH4uFCP0cQi4fdwjEsgzTTib4n/BLkeDH5MJVZu7KxT5KOqSUoTgd79BLfb42WKO0uoekpwmRCwfgqwUp3r0qKO0mbdpivKsPmjExp8pzLlWkIMC0XucrqkIv+7E0evnWXtgxrGZvqxJCcQC2+fD1njWf+4hUHhORVYIlXgzIRh94yQI5QTK8ZEt+57U6DXDjuQe5dkuRkZy8ROnfCMw78vf0PAhlUxG+hbBY//3RUaizpkDGVaiR09aS8cwcmloQlpC6B1+mQoBL+5+wrHs2ttNB8/xbxne2rygzC09qmWTg78X/wvtQn/mibVUw3RMa/n51aB8KjHNFArVencSIdJtZU7kx4WJatABoKRwy4gc9aWCAf5YfhHWbuSt0No6xjQWLZfQ27osjYXOfYvBd2JpUBEWdIhpv7g5U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
