travis:
  secure:
    BINSTAR_TOKEN: d+TTRJX9YPeyFoAFGZPFMLs0/LJn94FymaMjq57EKleewmNncKkGoB4yQHNN+92XHd+J185ZTkPW/lTi8uu8TPIZwpoNi07bOy3/Tcu+VXWDQit4L1koj/2dMrW4JSU7MLOUnRay6ZzfQSSHjIQEJWyuSugrxjhRy6vlzYMdqqf2iGm+ZdHgWh+B9twViKy8GYTX4p1u+y9mfVrBvRUsN/aXWGyaV39QRbAUL9QfjN8b013pzcQ3tAaJcfhiBRmf+4Xl2+pZXUnXourfejxG9jXnt/CsLI3SDGRsS6IufAUQzDwFre4p5yYwq5TwTDPjMFfzSUO/MK2QsrP9Ckq7zXCFjXITAzQOd8wH5j8CmLrUCuFCDhKHUiHz/wqrGI0h7WXnIsyowKm6o1j2FhFjCRYXt4DiS5ttT04UxRZZrE0K6T5Fv+XEih0wFfLRx9S4Vgj/MAS2ct2LadJvN7jvBzXuTksIK1MIonu7TUnvz5BvQ8vaz+L7FdhLedxzU8UFPVQSao9m9HsuYPFaNsvnfANYKsRAmMUhKoabuwXvfOOoPWHfNDXIPBzkW6+2X3K4xtSsKnQKVE0H7+kK1HF0wU5vMcFpn0LUL3yPiCZGVN89chwaAUGzofkjzh93bTMhYxkke3b44Oi/qWmcfyMvjzppWA8CqHW7zK8FNUp7l+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
