appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: bvwU//r9pVnuSKsZZ69NXndUJKAgj/RsA+osl+x/90HGhxB78GBD/JObWk+gv9PYMiZ9K80TsJ7Y92IrUrP3scOSNLjelRxYTwvGCPWBEXBCWzF39Uk7CB3K/97LACg13SmZwPPG0rrdyKFkeolYpskJcI4yhXrSig8mG1UU2Mdm7W+o2yn9J8vMoKYymBI/IYBK1Ggh3Vj4oB4MgOjTr4Kbv2lntyxgUd77Ab9OmtF4tVMFuBarGMSSMnrexhITi3bmtYxYX5K2o9KLyt2vIDT1+UNNYItqiHiXestE5QZFH3CPGGdmkHUhcUT6qc4Lwfw15fVRL0GCe4F6G7eSn4epZTrwCCvDR94bAZ95SEkueuQwfgxBu7tqfSSwr2omI/31NbtiAf/cx59qu2RZY6kz+LyTf3MF20P5uakY6Ms4XfRRR4yVUrUoZRKUw78y2uXBkpsR79/FQAYthn47ju7nTZxhAFZokrB4sVYBuVliLsGGo5ExKjEejuqubtgNeV6kPZQGysCl8O5q0w5ww17QhpM7wtccHMFVndE4t2A245sHssuO0pIXxvVFPuKQRh7UXBLWjgR3x+aVDjAEFStQc96LTHXnrQle1Fx89WJtcM0BREaPQSz1YjpuNs8Y+46cG+33+SxHavdrPHZ+U00pPUoFnLpWvqbm0kTJdas=}
bot:
  automerge: true
