travis:
  secure:
    BINSTAR_TOKEN: L0SSy3xsNd/HMXUeq8o8ukc83jqGNbtQHSJvZReBl+cj1W0n6iTeDWdAj2H0fSR2eM8+M7zMAWnNuJX+rQlCcx+nPU7yJw3mCYv/JFB8uSJHMj3rZxbiw2G+qDNThCugrB5hjxBKQyS30zy6hJLH8a7Tix4J4pBoZbd9nH3wXtRmt7u0bdNLGhCGVEmoJvye4byu/m7u+Dykuf94/CB72nayaIIvjtlfkNb2BGtWLdrpjpDXd0ym0EAWgkn/ArvYLz5f6ET5rp2Eb9zLN8NjFnuqZAbryTbXcuuPaKnVFEFaBufFTmsUdy3+toAiaBTYF3JUzLJk27XaSW4nSBa9XuxSwLfop7tv15XjpJ3CikChPJOS5Z/gizOBmrcV6kA1q80pNzCkiQUl1Bp+7ML7LoEJu9tKV3+11W3fjWNxiSB4YPsYiuX5YZqZW2XNq6MOOexyWUhrytfdATsjGNE3UhJ/i7hALVqjnip8dkTH+Qf7m2v1PEL3S92WbRYsI3q2rvYO+/tX0t8KXiVOtqqjbVb73b+59waPcOoAHWzs2Wl0IQNW41bYfIwlOjF9M2IDl+cYyXwAS+DS04MwFbioQ2W2Ln3bC8rRXy/RR6IA89v75hobpicA8bJNP6V1ad8obOk/HA5wCM0qheAMJFQFslTUO2xfkqlgHxGLBgTD6Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
